services:
  - type: web
    name: xauusd-ai-api
    env: python
    plan: free
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000

